drop table member2 cascade constraints;
drop table my_habit cascade constraints;
drop table challenge cascade constraints;
drop table proof cascade constraints;
drop table review cascade constraints;
drop table my_result cascade constraints;
drop table challenge_members cascade constraints;
drop table challenge_result cascade constraints;

drop sequence "MY_HABIT_SEQ";
drop sequence "CHALLENGE_SEQ";
drop sequence "PROOF_SEQ" ;
drop sequence "REVIEW_SEQ" ;
drop sequence "MY_RESULT_SEQ" ;
drop sequence "CHALLENGE_MEMBERS_SEQ" ;
drop sequence "CHALLENGE_RESULT_SEQ" ;

/** 시퀀스 몰아쓰기 **/

CREATE SEQUENCE  "MY_HABIT_SEQ" MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 1 ;
CREATE SEQUENCE  "CHALLENGE_SEQ"  MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 1 ;
CREATE SEQUENCE  "PROOF_SEQ" MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 1 ;
CREATE SEQUENCE  "REVIEW_SEQ" MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 1 ;
CREATE SEQUENCE  "MY_RESULT_SEQ" MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 1 ;
CREATE SEQUENCE  "CHALLENGE_MEMBERS_SEQ" MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 1 ;
CREATE SEQUENCE  "CHALLENGE_RESULT_SEQ" MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 1 ;

/**맴버테이블생성**/

CREATE TABLE "MEMBER2"
   (   "M_ID" VARCHAR2(30 BYTE), 
   "NICKNAME" VARCHAR2(20 BYTE), 
   "PW" VARCHAR2(20 BYTE), 
   "NAME" VARCHAR2(20 BYTE), 
   "TEL" VARCHAR2(20 BYTE), 
   "GENDER" VARCHAR2(20 BYTE), 
   "JOB" VARCHAR2(30 BYTE), 
   "EMAIL" VARCHAR2(30 BYTE), 
   "HABIT" VARCHAR2(30 BYTE), 
   "POINT" NUMBER
   );

  ALTER TABLE "MEMBER2" ADD CONSTRAINT "MEMBER2_PK" PRIMARY KEY ("M_ID") ENABLE;
  ALTER TABLE "MEMBER2" MODIFY ("M_ID" NOT NULL ENABLE);
  ALTER TABLE "MEMBER2" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "MEMBER2" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MEMBER2" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "MEMBER2" MODIFY ("TEL" NOT NULL ENABLE);
  ALTER TABLE "MEMBER2" MODIFY ("EMAIL" NOT NULL ENABLE);

/** myhabit 테이블 생성**/

  CREATE TABLE "MY_HABIT" 
   (   "H_ID" NUMBER, 
   "M_ID" VARCHAR2(30 BYTE), 
   "H_NAME" VARCHAR2(100 BYTE), 
   "H_DAY" VARCHAR2(50 BYTE), 
   "H_STARTDATE" VARCHAR2(100 BYTE), 
   "H_ENDDATE" VARCHAR2(20 BYTE), 
   "H_ALARM" VARCHAR2(100 BYTE)
   );

  ALTER TABLE "MY_HABIT" ADD CONSTRAINT "MY_HABIT_PK" PRIMARY KEY ("H_ID") ENABLE;
  ALTER TABLE "MY_HABIT" MODIFY ("H_ID" NOT NULL ENABLE);
  ALTER TABLE "MY_HABIT" MODIFY ("M_ID" NOT NULL ENABLE);
  ALTER TABLE "MY_HABIT" MODIFY ("H_NAME" NOT NULL ENABLE);
  ALTER TABLE "MY_HABIT" MODIFY ("H_DAY" NOT NULL ENABLE);
  ALTER TABLE "MY_HABIT" MODIFY ("H_STARTDATE" NOT NULL ENABLE);
     
/** challenge 테이블 생성**/

  CREATE TABLE "CHALLENGE" 
   (   "CH_ID" NUMBER, 
   "M_ID" VARCHAR2(30 BYTE),
   "CH_NAME" VARCHAR2(100 BYTE), 
   "NUM" NUMBER, 
   "CH_DAY" VARCHAR2(50 BYTE), 
   "STARTDATE" VARCHAR2(40 BYTE), 
   "ENDDATE" VARCHAR2(40 BYTE), 
   "CH_CONTENT" VARCHAR2(150 BYTE), 
   "ALARM" VARCHAR2(100 BYTE), 
   "CH_FILE" VARCHAR2(50 BYTE)
   ) ;

  ALTER TABLE "CHALLENGE" ADD CONSTRAINT "CHALLENGE_PK" PRIMARY KEY ("CH_ID") ENABLE;
  ALTER TABLE "CHALLENGE" MODIFY ("CH_ID" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE" MODIFY ("M_ID" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE" MODIFY ("CH_NAME" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE" MODIFY ("NUM" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE" MODIFY ("CH_DAY" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE" MODIFY ("STARTDATE" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE" MODIFY ("CH_CONTENT" NOT NULL ENABLE);

  
  /** proof 테이블 생성**/

  CREATE TABLE "PROOF" 
   (	"PRF_ID" NUMBER, 
	"CH_ID" NUMBER, 
	"M_ID" VARCHAR2(30BYTE), 
	"PRF_DATE" VARCHAR2(50 BYTE), 
	"CH_POINT" NUMBER,
	"PRF_FILE" VARCHAR2(100 BYTE) 
   ) ;

  ALTER TABLE "PROOF" ADD CONSTRAINT "PROOF_PK" PRIMARY KEY ("PRF_ID") ENABLE;
  ALTER TABLE "PROOF" MODIFY ("PRF_DATE" NOT NULL ENABLE);
  ALTER TABLE "PROOF" MODIFY ("M_ID" NOT NULL ENABLE);
  ALTER TABLE "PROOF" MODIFY ("CH_ID" NOT NULL ENABLE);
  ALTER TABLE "PROOF" MODIFY ("PRF_ID" NOT NULL ENABLE);

/** review 테이블 생성**/
  
  CREATE TABLE "REVIEW" 
   (	"R_ID" NUMBER, 
   "CH_ID" NUMBER, 
	"M_ID" VARCHAR2(30 BYTE), 
	"R_DATE" VARCHAR2(100 BYTE), 
	"R_POINT" NUMBER,
	"R_FILE" VARCHAR2(50 BYTE) 
   ) ;

  ALTER TABLE "REVIEW" ADD CONSTRAINT "REVIEW_PK" PRIMARY KEY ("R_ID") ENABLE;
  ALTER TABLE "REVIEW" MODIFY ("R_ID" NOT NULL ENABLE);
  ALTER TABLE "REVIEW" MODIFY ("CH_ID" NOT NULL ENABLE);
  ALTER TABLE "REVIEW" MODIFY ("M_ID" NOT NULL ENABLE);
  ALTER TABLE "REVIEW" MODIFY ("R_DATE" NOT NULL ENABLE);

  /** myresult 테이블 생성**/
  
  CREATE TABLE "MY_RESULT" 
   (	"MR_ID" NUMBER, 
	"H_ID" NUMBER, 
	"M_ID" VARCHAR2(20 BYTE),
	"MR_DATE" VARCHAR2(50 BYTE), 
	"MR_RESULT" VARCHAR2(30 BYTE), 
	"MR_POINT" NUMBER
   ) ;

  ALTER TABLE "MY_RESULT" ADD CONSTRAINT "MY_RESULT_PK" PRIMARY KEY ("MR_ID") ENABLE;
  ALTER TABLE "MY_RESULT" MODIFY ("MR_ID" NOT NULL ENABLE);
  ALTER TABLE "MY_RESULT" MODIFY ("H_ID" NOT NULL ENABLE);
  ALTER TABLE "MY_RESULT" MODIFY ("M_ID" NOT NULL ENABLE);
  ALTER TABLE "MY_RESULT" MODIFY ("MR_DATE" NOT NULL ENABLE);
  ALTER TABLE "MY_RESULT" MODIFY ("MR_RESULT" NOT NULL ENABLE);

/** challengemembers 테이블 생성**/

  CREATE TABLE "CHALLENGE_MEMBERS" 
   (	"CHM_ID" NUMBER, 
	"CH_ID" NUMBER, 
	"M_ID" VARCHAR2(20 BYTE), 
	"PRF_ID" NUMBER
   ) ;

  ALTER TABLE "CHALLENGE_MEMBERS" ADD CONSTRAINT "CHALLENGE_MEMBERS_PK" PRIMARY KEY ("CHM_ID") ENABLE;
  ALTER TABLE "CHALLENGE_MEMBERS" MODIFY ("CHM_ID" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE_MEMBERS" MODIFY ("CH_ID" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE_MEMBERS" MODIFY ("M_ID" NOT NULL ENABLE);

  /** challengeresult 테이블생성**/
  
  CREATE TABLE "CHALLENGE_RESULT" 
   (	"CH_ID" NUMBER, 
	"CHM_ID" NUMBER, 
	"PRF_ID" NUMBER, 
	"CHR_DATE" VARCHAR2(100 BYTE), 
	"CHR_RESULT" VARCHAR2(20 BYTE)
   ) ;

  ALTER TABLE "CHALLENGE_RESULT" ADD CONSTRAINT "CHALLENGE_RESULT_PK" PRIMARY KEY ("CH_ID") ENABLE;
  ALTER TABLE "CHALLENGE_RESULT" MODIFY ("CH_ID" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE_RESULT" MODIFY ("CHM_ID" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE_RESULT" MODIFY ("PRF_ID" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE_RESULT" MODIFY ("CHR_DATE" NOT NULL ENABLE);
  ALTER TABLE "CHALLENGE_RESULT" MODIFY ("CHR_RESULT" NOT NULL ENABLE);

  /** foreign key 몰아넣음**/
  
  ALTER TABLE "MY_HABIT" ADD CONSTRAINT "MY_HABIT_FK1" FOREIGN KEY ("M_ID")
      REFERENCES "MEMBER2" ("M_ID") ENABLE;
      
  ALTER TABLE "CHALLENGE" ADD CONSTRAINT "CHALLENGE_FK1" FOREIGN KEY ("M_ID")
      REFERENCES "MEMBER2" ("M_ID") ENABLE;
  
  ALTER TABLE "PROOF" ADD CONSTRAINT "PROOF_FK1" FOREIGN KEY ("CH_ID")
	  REFERENCES "CHALLENGE" ("CH_ID") ENABLE;
  ALTER TABLE "PROOF" ADD CONSTRAINT "PROOF_FK2" FOREIGN KEY ("M_ID")
	  REFERENCES "MEMBER2" ("M_ID") ENABLE;  
	  
  ALTER TABLE "REVIEW" ADD CONSTRAINT "REVIEW_FK1" FOREIGN KEY ("CH_ID")
	  REFERENCES "CHALLENGE" ("CH_ID") ENABLE;
  ALTER TABLE "REVIEW" ADD CONSTRAINT "REVIEW_FK2" FOREIGN KEY ("M_ID")
	  REFERENCES "MEMBER2" ("M_ID") ENABLE;
	  
  ALTER TABLE "MY_RESULT" ADD CONSTRAINT "MY_RESULT_FK1" FOREIGN KEY ("H_ID")
	  REFERENCES "MY_HABIT" ("H_ID") ENABLE;
  ALTER TABLE "MY_RESULT" ADD CONSTRAINT "MY_RESULT_FK2" FOREIGN KEY ("M_ID")
	  REFERENCES "MEMBER2" ("M_ID") ENABLE;
	  
  ALTER TABLE "CHALLENGE_MEMBERS" ADD CONSTRAINT "CHALLENGE_MEMBERS_FK1" FOREIGN KEY ("CH_ID")
	  REFERENCES "CHALLENGE" ("CH_ID") ENABLE;
  ALTER TABLE "CHALLENGE_MEMBERS" ADD CONSTRAINT "CHALLENGE_MEMBERS_FK2" FOREIGN KEY ("M_ID")
	  REFERENCES "MEMBER2" ("M_ID") ENABLE;
  ALTER TABLE "CHALLENGE_MEMBERS" ADD CONSTRAINT "CHALLENGE_MEMBERS_FK3" FOREIGN KEY ("PRF_ID")
	  REFERENCES "PROOF" ("PRF_ID") ENABLE;
  
  ALTER TABLE "CHALLENGE_RESULT" ADD CONSTRAINT "CHALLENGE_RESULT_FK1" FOREIGN KEY ("CH_ID")
	  REFERENCES "CHALLENGE" ("CH_ID") ENABLE;
  ALTER TABLE "CHALLENGE_RESULT" ADD CONSTRAINT "CHALLENGE_RESULT_FK2" FOREIGN KEY ("PRF_ID")
	  REFERENCES "PROOF" ("PRF_ID") ENABLE;
  ALTER TABLE "CHALLENGE_RESULT" ADD CONSTRAINT "CHALLENGE_RESULT_FK3" FOREIGN KEY ("CHM_ID")
	  REFERENCES "CHALLENGE_MEMBERS" ("CHM_ID") ENABLE;	  
	  
commit
	  SELECT * FROM CHALLENGE;
	  SELECT * FROM CHALLENGE_MEMBERS;
	  SELECT * FROM CHALLENGE_RESULT;
	  SELECT * FROM MEMBER2;
	  SELECT * FROM MY_HABIT;
	  SELECT * FROM MY_RESULT;
	  SELECT * FROM PROOF;
	  SELECT * FROM REVIEW;